name: audiobook_player
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  just_audio: ^0.9.31
  just_audio_mpv: any
  file_picker: ^5.2.5
  path_provider: ^2.0.11
  uuid: ^3.0.6
  permission_handler: ^10.2.0
  on_audio_query: ^2.6.0
  


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Enable generation of localized Strings from arb files.
  generate: true